config = [
	'--all_datasets False',
	'--datasets affectnet_short',
	'--img_size 64',
	'--transform classic',
	'--val_split 0.1',
	'--split_seed 18',
	'--epochs 50',
	'--batch_size 4',
	'--num_workers 12',
	'--checkpoint None',
	'--save_every 1',
	'--optimizer Adam',
	'--lr_scheduler None',
	'--model vggtransformer',
	'--num_encoder_layers 1',
	'--num_decoder_layers 1',
	'--num_heads 4',
	'--vgg_emb_size 128',
]
